const { registerComponent } = require('mjml-core');

const OlaButton = require('./src/OlaButton');
const OlaCounter = require('./src/OlaCounter');
const OlaDivider = require('./src/OlaDivider');
const OlaFooterMessage = require('./src/OlaFooterMessage');
const OlaFooterAddress = require('./src/OlaFooterAddress');
const OlaFooterMenu = require('./src/OlaFooterMenu');
const OlaFooterMenuLink = require('./src/OlaFooterMenuLink');
const OlaFooterMenuIcon = require('./src/OlaFooterMenuIcon');
const OlaHead = require('./src/OlaHead');
const OlaHeader = require('./src/OlaHeader');
const OlaHero = require('./src/OlaHero');
const OlaHeroImg = require('./src/OlaHeroImg');
const OlaHeroTitle = require('./src/OlaHeroTitle');
const OlaItemList = require('./src/OlaItemList')
const OlaPanel = require('./src/OlaPanel');
const OlaPanelSection = require('./src/OlaPanelSection');
const OlaPanelSignature = require('./src/OlaPanelSignature');
const OlaPanelText = require('./src/OlaPanelText');
const OlaPanelTitle = require('./src/OlaPanelTitle');
const OlaProgressBar = require('./src/OlaProgressBar');
const OlaScore = require('./src/OlaScore');
const OlaTask = require('./src/OlaTask');
const OlaText = require('./src/OlaText');
const OlaThumbnail = require('./src/OlaThumbnail');
const OlaTag = require('./src/OlaTag');

registerComponent(OlaButton);
registerComponent(OlaCounter);
registerComponent(OlaDivider);
registerComponent(OlaFooterMessage);
registerComponent(OlaFooterAddress);
registerComponent(OlaFooterMenu);
registerComponent(OlaFooterMenuLink);
registerComponent(OlaFooterMenuIcon);
registerComponent(OlaHead);
registerComponent(OlaHeader);
registerComponent(OlaHero);
registerComponent(OlaHeroImg);
registerComponent(OlaHeroTitle);
registerComponent(OlaItemList);
registerComponent(OlaPanel);
registerComponent(OlaPanelSection);
registerComponent(OlaPanelSignature);
registerComponent(OlaPanelText);
registerComponent(OlaPanelTitle);
registerComponent(OlaProgressBar);
registerComponent(OlaScore);
registerComponent(OlaTask);
registerComponent(OlaText);
registerComponent(OlaThumbnail);
registerComponent(OlaTag);
