const { registerComponent } = require('mjml-core');

const OlaButton = require('./OlaButton');
const OlaFooterMessage = require('./OlaFooterMessage');
const OlaFooterAddress = require('./OlaFooterAddress');
const OlaFooterMenu = require('./OlaFooterMenu');
const OlaFooterMenuLink = require('./OlaFooterMenuLink');
const OlaFooterMenuIcon = require('./OlaFooterMenuIcon');
const OlaHeader = require('./OlaHeader');
const OlaHero = require('./OlaHero');
const OlaHeroHeader = require('./OlaHeroHeader');
const OlaHeroImg = require('./OlaHeroImg');
const OlaPanel = require('./OlaPanel');
const OlaPanelSection = require('./OlaPanelSection');
const OlaSignature = require('./OlaSignature');
const OlaText = require('./OlaText');

registerComponent(OlaButton);
registerComponent(OlaFooterMessage);
registerComponent(OlaFooterAddress);
registerComponent(OlaFooterMenu);
registerComponent(OlaFooterMenuLink);
registerComponent(OlaFooterMenuIcon);
registerComponent(OlaHeader);
registerComponent(OlaHero);
registerComponent(OlaHeroHeader);
registerComponent(OlaHeroImg);
registerComponent(OlaPanel);
registerComponent(OlaPanelSection);
registerComponent(OlaSignature);
registerComponent(OlaText);
