name: Demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm i
      - run: npm run build:demo
      - run: npm run build:docs
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.0.1
        with:
          build_dir: demo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}